apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: argocd-example-apps
    repoURL: https://github.com/alwesto/argo-from-scratch.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true